### PR TITLE
Add 8.x mpy type

### PR DESCRIPTION
**Pull request by Kriechi**

### CODE REVIEW

**Comment by makermelissa** [comment]
Could you remove the 6mpy option? The contents are missing from the bundle, so it won't work anyways.

**Review by makermelissa — CHANGES_REQUESTED** [review]
Could you remove the 6mpy option? The contents are missing from the bundle, so it won't work anyways.

**Comment by Kriechi** [comment]
@makermelissa 6mpy is currently also the default - should I bump the default to 7mpy or go straight to 8mpy?
or remove the default and require the user to specify an option explicitly?

**Comment by makermelissa** [comment]
Oh, good point. Let's make 7mpy the default.

**Comment by Kriechi** [comment]
done!

**Review by makermelissa — APPROVED** [review]
Awesome. Thank you so much. :)

**Pull request merged**
